### ISSUE TITLE
[Bug]: Nothing showing in the log when run thor with sudo.

### ISSUE THREAD

**Issue by Kreuger** [ethical-haquer/Galaxy-Flasher#15] opened 2024-07-03 15:14 UTC
### What happened?

I loaded the program fine at first. When I tried clicking connect it gave me an error "fail to find valid endpoints". I had toggled run thor with sudo on so I thought maybe I needed to restart the app for it to work properly. Now when it opens, I don't see anything on the log screen and can't click connect or anything else. The only buttons that work are the tabs and the file selection buttons. If I try to run the flatpak command with sudo infront, it says that I don't have GF installed. If I turn off "run with sudo" then it will load fine but I'm back to the error about valid endpoints. Can we maybe have it prompt for a SU password (for example as an Lubuntu user, it would use lxqt-sudo)?

### Galaxy Flasher version

Alpha v0.5.0

### Galaxy Flasher's log output

```shell
n/a
```

### Flash tool's log output

```shell
n/a
```

**Comment by ethical-haquer** [comment] 2024-07-03 16:56
Thanks for reporting this!
So yes, currently the "Run Thor with sudo" setting only applies upon restart.
As for the "Failed to find valid endpoints!" error, that is this issue: https://github.com/Samsung-Loki/Thor/issues/9. So far no one knows how to fix it (or even what causes it). In short, there's not much I can do about that.
Now about that issue you're having with using sudo, that's because Galaxy Flasher disables buttons until it detects "[sudo] password for" in the output. Perhaps your sudo prompt uses a different format? If so, please let me know what's displayed in the Log Tab after the app starts up (with "Run Thor with sudo" enabled). Thanks!

**Comment by Kreuger** [comment] 2024-07-03 20:56
Absolutely nothing shows in the log tab at all when I launch it with sudo enabled. Where is it supposed to prompt for my password?

**Comment by ethical-haquer** [comment] 2024-07-04 13:52
It's _supposed_ to look like this:
![Galaxy-Flasher-Thor-sudo-prompt](https://github.com/ethical-haquer/Galaxy-Flasher/assets/141518185/91c2a7e9-2dd3-4462-aec6-e63af8ce80fe)
However, after testing it on my system, I actually got the same result! 🤣
Apparently, the issue only effects the flatpaks. I will look into what needs to be done to fix this, and hopefully have it fixed in the next release. In the meantime, have you tried using Odin4?
Thanks for alerting me to this!

**Comment by justaCasualCoder** [comment] 2024-07-04 18:31
@ethical-haquer 
The issue is simple, `sudo` is not included in the `org.gnome.Platform` flatpak:
```bash
flatpak run --command=sudo com.ethicalhaquer.galaxyflasher
bwrap: execvp sudo: No such file or directory
```
The option should probably be disabled in flatpak anyway, because it won't do anything (the host needs to give permissions, not the flatpak).

**Comment by ethical-haquer** [comment] 2024-07-05 16:43
@justaCasualCoder
Sorry, I meant fixing the "Run Thor with sudo" setting not working with the flatpak. I don't really like bundling the flash-tools with the app, because it makes the release almost 80Mbs. If you're on x64 you don't need the arm64 version of Thor. We could have multiple different release files for different platforms, but I was thinking the app would let you choose a file to use (like in prev releases) and maybe also allow downloading them. So, as I'm sure you know, you can't run a sudo command in the sandbox. This is what I've come up with so far:
```
# Add this line to the finish-args in com.ethicalhaquer.galaxyflasher.yml for this to work:
# "- --talk-name=org.freedesktop.Flatpak"
if self.settings.get("sudo", False) and self.flashtool == "thor":
                # This would still be used if the app isn't a flatpak, I think.
                # flashtool_exec = ["sudo", flashtool_path]
                # For a flatpak.
                flashtool_exec = [
                    "flatpak-spawn",
                    "--host",
                    "--env=TERM=xterm-256color",
                    "--directory=/home/ethical_haquer",
                    "sudo",
                    "-S",
                    "./TheAirBlow.Thor.Shell",
                ]
```
Obviously without the hard-coded values though. What are your thoughts on this?

**Comment by Kreuger** [comment] 2024-07-05 22:23
I think if youre going to do separate releases, you might as well do deb/rpm/etc. The idea of a flatpak is one single package for all, to make releases easier right? I dont think 80mb is a lot.

**Comment by ethical-haquer** [comment] 2024-07-09 01:31
@Kreuger, @justaCasualCoder

> I think if youre going to do separate releases, you might as well do deb/rpm/etc. The idea of a flatpak is one single package for all, to make releases easier right? I dont think 80mb is a lot.

Yeah, doing separate releases might be something for in the future, but for now Galaxy Flasher just needs to get on FlatHub. And yes, 80Mb isn't a ton, but if it can be made smaller, that's better. Especially with people with slow internet speeds.

This is what the improved flash-tool setting I'm working on looks like right now:
![new-flash-tool-setting](https://github.com/ethical-haquer/Galaxy-Flasher/assets/141518185/405648ce-8a27-4a9e-b337-14b9bcbf38ea)

**Comment by justaCasualCoder** [comment] 2024-07-09 13:44
@ethical-haquer 
It looks good! About the "Run Thor with Sudo" in Flatpak, that looks good too, but running Thor with `sudo` is not really the proper way to do it. Adding a `udev` rule would be better (or telling the user how to).

**Comment by ethical-haquer** [comment] 2024-07-09 18:23
@justaCasualCoder 
You're right, the "Run Thor with sudo" setting should be removed.
I'll look into making adding the udev rule easier.

**Comment by ethical-haquer** [comment] 2024-08-05 16:02
@Kreuger 
This issue was fixed in [Alpha v0.5.1](https://github.com/ethical-haquer/Galaxy-Flasher/releases/tag/v0.5.1-alpha). 
If you get a chance to try it let me know what you think!

**Comment by ethical-haquer** [comment] 2024-08-05 16:03
@Kreuger 
This issue was fixed in [Alpha v0.5.1](https://github.com/ethical-haquer/Galaxy-Flasher/releases/tag/v0.5.1-alpha). 
If you get a chance to try it let me know what you think!

**Closed by ethical-haquer** 2024-08-05 16:03 UTC
Labels: bug

**Comment by Kreuger** [comment] 2024-08-05 20:43
I am unable to build the new release. I have posted a log [here](url=https://paaster.io/81I8n63h0gc3tp6PUwY5b#myeEb8OO4UencHoLv3760Iq4Wgu60Qpk3jp33ePwEh8) showing the output.

**Comment by ethical-haquer** [comment] 2024-08-05 23:11
> I am unable to build the new release. I have posted a log [here](https://paaster.io/81I8n63h0gc3tp6PUwY5b#myeEb8OO4UencHoLv3760Iq4Wgu60Qpk3jp33ePwEh8) showing the output.

Thanks for the info. I uploaded a new release file, it should be fixed now.

**Comment by Kreuger** [comment] 2024-08-07 16:48
Ill try it again later today.

**Comment by Kreuger** [comment] 2024-08-08 20:36
I was able to install it no problem but it doesn't seem to detect my phone. I tried doing it with my phone mounted and unmounted, nothing. The connect button just stays greyed out. Also, it doesn't seem to remember which tool you set upon restart.

**Comment by ethical-haquer** [comment] 2024-08-09 00:22
> I was able to install it no problem but it doesn't seem to detect my phone. I tried doing it with my phone mounted and unmounted, nothing. The connect button just stays greyed out. Also, it doesn't seem to remember which tool you set upon restart.

The settings file, which is called "settings.json" is located at `~/.var/app/com.ethicalhaquer.galaxyflasher/config/galaxy-flasher`. The contents of that are human-readable, here's what mine looks like:
`
{"odin4_file": "/home/ethical_haquer/odin4", "flash_tool": "odin4", "auto_partitions": false, "theme": "system", "thor_file": "/home/ethical_haquer/TheAirBlow.Thor.Shell", "keep_log_dark": true, "pythor_file": "/home/ethical_haquer/pythor_cli"}
`

The README doesn't have this info, but the first time you run Galaxy Flasher, you have to select a flash-tool to use in settings. For example, in this screenshot an Odin4 executable hasn't been selected, so you will be prompted to select one if you choose it:
![odin4-not-set](https://github.com/user-attachments/assets/4ac4fc7a-6687-42af-9659-265741b3e083)

It sounds like you are already trying to do that though.
Is there ever any output in the Log Tab?
If so, could you copy/paste it here? (right click in the Log Tab to copy).
Sorry that it's causing so many problems for you, hopefully I can figure out why it's doing that. TIA.

**Comment by Kreuger** [comment] 2024-08-10 23:04
Yes I was trying to set the flash tool. Nothing shows in the log tab except that it tells me to set a flash tool. I tried setting both thor and odin4 and nothing else appears. When I run it from the terminal it says "flash_tool set to: thor/odin4" but nothing else after. Is the problem that my phone needs to be in recovery phone to work? Also it's not a big deal, I can't actually flash anything to my phone. I just wanted to try it out and seeing as I found some issues, I thought I'd help out by reporting them for you.

**Comment by ethical-haquer** [comment] 2024-08-11 04:37
Yeah, once you set the flash-tool, close GF, and then restart it, the flash-tool should be set to what you chose. This is the output you should expect to see after setting the flash-tool:
```
Selected Thor executable: /home/ethical_haquer/TheAirBlow.Thor.Shell
thor_file set to: '/home/ethical_haquer/TheAirBlow.Thor.Shell'
flash_tool set to: 'thor'
```

It is prompting you to select a flash-tool executable (with a file-picker), right?

Your phone doesn't even need to be connected to your computer, unless your actually connecting/flashing it. That's not the issue.

Also, the var folder is hidden (".var"). Maybe that's why couldn't find it? There's also a chance that the config folder is somewhere else on your system, let me know if that's the case.

Once again, I'm really sorry it's causing this many issues for you. I understand that you aren't actually using it, and it's not a big deal for you, but as long as I'm not irritating you with all these questions, I would like to figure out what the problem is. If you get tired of me, please just let me know! :smile:

**Comment by Kreuger** [comment] 2024-08-12 01:03
Ah see I havent been using the file picker because for some silly reason, I didnt think I needed to. I thought both thor and odin were bundled and the file picker was for if you had them installed already and wanted to use your own for whatever reason. 

I only plugged my phone in when I had noticed that the connect button was greyed out.

I found the var folder. I didnt realize it was in the user directory. I was looking in the system /var/ folder. 

Are you planning to release an actual flatpak file at some point that doesnt require the user compiling it themself?

**Comment by ethical-haquer** [comment] 2024-08-12 14:50
If you click the "info" icons for the flash-tools, they will give you some info about the flash-tools, along with a link to download them:
![info-button](https://github.com/user-attachments/assets/983b72c0-904e-496f-af54-0ac30c203cc8)
For Thor, It's programmed in C#, which needs .NET to run. However, I built an executable that is self-contained, and doesn't require .NET to be installed. The link for it is included in the info dialog.


All of this info should be in the documentation, but it's not yet. I hope to have the documentation on something like Read The Docs in the near future. Also, yes, there will be a flatpak at some point. First GF needs a logo, and some further improvements. But yeah, that's definitely the plan. If possible, there could be packages for Debian/Ubuntu, Arch, etc. as well, at some point.

**Comment by Kreuger** [comment] 2024-08-12 22:24
Thanks. I somehow missed the link for the selfcontained file.

**Comment by ethical-haquer** [comment] 2024-08-13 03:02
Yeah, it says: "You have to run Thor as root or edit udev rules as follows.." even after you edit the udev rules. And the "Run Thor with sudo" setting was removed since editing the udev rules is the "proper" way of doing it. In future versions I hope to make editing the udev rules something GF does for you. As for the "Failed to download "usb.ids"" message, that is not a big deal, as it always showed you device as an S2, regardless of what is was. I'm realizing now that it probably shows that message because it doesn't have access to the internet, to download it. I may revert the changes I made that removed copying that file, as that will prevent the error from showing, but yeah, it'll just show "unknown device" instead of "Samsung S2". Also feel free to try Odin4, the link to download it is in it's info dialog. I really appreciate you trying out the app again, reporting bugs, and answering questions!

**Comment by Kreuger** [comment] 2024-08-15 00:21
> Yeah, it says: "You have to run Thor as root or edit udev rules as follows.." even after you edit the udev rules. And the "Run Thor with sudo" setting was removed since editing the udev rules is the "proper" way of doing it. In future versions I hope to make editing the udev rules something GF does for you. As for the "Failed to download "usb.ids"" message, that is not a big deal, as it always showed you device as an S2, regardless of what is was. I'm realizing now that it probably shows that message because it doesn't have access to the internet, to download it. I may revert the changes I made that removed copying that file, as that will prevent the error from showing, but yeah, it'll just show "unknown device" instead of "Samsung S2". Also feel free to try Odin4, the link to download it is in it's info dialog. I really appreciate you trying out the app again, reporting bugs, and answering my questions!

I couldnt get it to run by sticking lxsudo infront of the command. It seems that it cant detect it being installed. I guess because I didnt install it system wide?

I tried creating the udev file and relaunching GF but it didnt seem to work. Also I believe that folder requires root access so I dont think you could have GF create/edit that file without the user doing it manually and setting the proper permissions.

I also toyed around with odin4 and even tried to use pythor. But none of them seem able to find my phone. And since I cant flash to it anyway, thats not a bit deal. Im just happy to try the program out and certainly dont mind testing - reporting issues.

**Comment by ethical-haquer** [comment] 2024-08-21 23:45
@Kreuger 
First of all, sorry for my delayed response!
What were you not able to run? GF?
So you have a `/etc/udev/rules.d/51-android.rules` file? If so, what is its contents?
What phone do you have?
TIA, and once again, sorry for the wait!

**Comment by Kreuger** [comment] 2024-08-22 01:25
No worries. Im actually on vacation so I will get back to you in a day or 2.

**Comment by Kreuger** [comment] 2024-08-25 23:53
Yes, I have created the file. 

> SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", MODE="0666", 
GROUP="robbie"


It's the Samsung Galaxy A54. What I couldn't run is the command for GF with lxsudo infront. It says it can't find flatpak.

> lxsudo /usr/bin/flatpak run --branch=master --arch=x86_64 --command=/app/bin/entry com.ethicalhaquer.galaxyflasher
> lxqt-sudo: Stripping child environment except for: DISPLAY,LANG,LANGUAGE,LC_ADDRESS,LC_ALL,LC_COLLATE,LC_CTYPE,LC_IDENTIFICATION,LC_MEASUREMENT,LC_MESSAGES,LC_MONETARY,LC_NAME,LC_NUMERIC,LC_PAPER,LC_TELEPHONE,LC_TIME,PATH,QT_PLATFORM_PLUGIN,QT_QPA_PLATFORMTHEME,TERM,WAYLAND_DISPLAY,XAUTHLOCALHOSTNAME,XAUTHORITY
> [sudo] password for robbie: 
> /bin/sh: 1: exec: /usr/bin/flatpak: not found

**Comment by ethical-haquer** [comment] 2024-08-26 00:37
@Kreuger 
It should just be `flatpak run com.ethicalhaquer.galaxyflasher`. What is the output of that command?

**Comment by Kreuger** [comment] 2024-08-27 23:05
> @Kreuger It should just be `flatpak run com.ethicalhaquer.galaxyflasher`. What is the output of that command?

Yeah Im not sure how I got that command, actually. I have a shortcut on my desktop and thats what is in there. But I cant remember how I made it. Your command works.

**Comment by ethical-haquer** [comment] 2024-08-28 02:10
@Kreuger 
You should just run it as a normal user, is there a reason why you want to run it as root?

**Comment by Kreuger** [comment] 2024-08-28 22:42
Because it says you have to run Thor as root.

**Comment by Kreuger** [comment] 2024-08-31 01:01
Yeah it didnt work so I tried to run the program as root.

**Comment by ethical-haquer** [comment] 2024-08-31 13:45
@Kreuger 
So the flash-tools start-up fine, but you're unable to connect your device still?

**Comment by Kreuger** [comment] 2024-08-31 23:13
Yeah it doesnt show up when using the list command.

**Comment by ethical-haquer** [comment] 2024-09-01 13:12
@Kreuger 
You have your device connected in Download Mode when you run list, right?

**Comment by Kreuger** [comment] 2024-09-02 14:13
No I didnt realize that was required.

**Comment by ethical-haquer** [comment] 2024-09-02 16:22
@Kreuger 
No worries. :sweat_smile:
Yeah, try just putting it in Download Mode and then connecting.
I've been working on the external docs for GF: they can be found [here](https://ethical-haquer-rtd-tutorial.readthedocs.io/en/latest/). I'm still working on them, of course.

**Comment by Kreuger** [comment] 2024-09-04 01:45
That did indeed work!

**Comment by ethical-haquer** [comment] 2024-09-04 11:55
@Kreuger 
Nice!
It should show up in Thor as well than, if you want to test that.
You said you couldn't flash your device, right? Is that because it's your daily driver, or something else?

**Comment by Kreuger** [comment] 2024-09-04 19:27
I can give that a try. But my bootloader isnt unlocked.

**Comment by ethical-haquer** [comment] 2024-09-04 20:44
@Kreuger 
Alright.
What model of the Galaxy A54 do you have?

**Comment by Kreuger** [comment] 2024-09-04 23:20
A546E/DS.

**Comment by ethical-haquer** [comment] 2024-09-05 00:11
@Kreuger 
Are you able to [enable OEM unlocking](https://xdaforums.com/t/which-models-support-oem-unlocking.4606435/#post-89114894) from developer settings?

**Comment by Kreuger** [comment] 2024-09-05 21:57
Yes I have it OEM unlocked.
